
--문제 :https://school.programmers.co.kr/learn/courses/30/lessons/164673
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY R  LEFT JOIN USED_GOODS_BOARD B               
ON B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE BETWEEN '2022-09-30'AND '2022-10-31'
ORDER BY R.CREATED_DATE, B.TITLE